name: Create UI-Designer Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version - keep --next-version to bump patch digit
          default: --next-patch
          required: true
      pushGithubTag:
        description: Push a github release
        required: true
        default: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: create github release
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: createGithubRelease
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          inputs: '{ "version": "${{ github.event.inputs.version }}" }'
          ref: ${{github.ref}}
        if: ${{ github.event.inputs.pushGithubTag }}
      - name: Publish
        uses: benc-uk/workflow-dispatch@v1.1
          with:
            workflow: publishBinaries
            token: ${{ secrets.GH_RELEASE_TOKEN }}
            inputs: '{ "tagVersion": "${{ github.event.inputs.version }}" }'
            ref: ${{github.ref}}
        if: ${{ github.event.inputs.pushGithubTag }}
