name: Create github tag
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version - keep --next-version to bump patch digit
        default: '--next-version'
        required: true
jobs:
  createGithubTag:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Config git
        run: |
          git config --local user.email "testBot@users.noreply.github.com"
          git config --local user.name "ui-designer-bot"
          git config pull.rebase true
      - name: Checkout master
#        run: git checkout ${{ github.event.inputs.baseBranch }} && git pull --tags
        run: git checkout ${{ github.ref }}
      - name: changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Get tag version
        id: newTagVersion
        shell: bash
        run: |
          if [ $1 = '--next-patch' ]
          then
              echo "##[set-output name=value;]$(./script/next-patch-version.sh)
          else
              echo "##[set-output name=value;]${{ github.event.inputs.version }}
          fi
      - name: Update Version
        shell: bash
        run: |
          ./script/update-version.sh ${{ steps.newTagVersion.outputs.value }}
          git commit -a -m "release(${{ steps.newTagVersion.outputs.value }}) create release ${{ steps.newTagVersion.outputs.value }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.newTagVersion.outputs.value }}
          release_name: Release ${{ steps.newTagVersion.outputs.value }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
#      - name: Git Tag
#        run: git tag ${{github.event.inputs.version}}
##      - name: Create a realGithub Release
#      - name: Push Release
#        run: git push --tags
