name: Create github Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: new version to release
        default: ''
        required: true
jobs:
  createGithubRelease:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Config git
        run: |
          git config --local user.email "ui-designer-bot@users.noreply.github.com"
          git config --local user.name "ui-designer-bot"
          git config pull.rebase true
      - name: Update Version
        shell: bash
        run: |
          ./script/update-version.sh ${{ github.event.inputs.version }}
          git commit -a -m "other(${{ github.event.inputs.version }}) create release ${{ github.event.inputs.version }}" && git tag -a ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"
          git push --tags
      - name: changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: true
      - name: Build binaries
#        run: mvn -B verify -Pe2e,integration-test
        run: mvn -B verify -DskipTests
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:
            backend/webapp/target/{*-standalone.jar,*.war}
          file_glob: true
          tag: ${{ github.event.inputs.version }}
          overwrite: true
