name: Release Pipeline
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Config git
        run: |
          git config --local user.email "testBot@users.noreply.github.com"
          git config --local user.name "ui-designer-bot"
          git config pull.rebase true
      - name: Checkout master
        run: git checkout master && git pull --tags
      - name: changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Update Version
        shell: bash
        run: ./script/update-version.sh ${{ github.event.inputs.version }}
      - name: Commit Pom update
        run: git commit -a -m "release(${{ github.event.inputs.version }}) create release ${{ github.event.inputs.version }}"
      - name: Git Tag
        run: git tag ${{github.event.inputs.version}}
      - name: Push Release
        run: git push --tags
