createRelease: Publish binaries
on:
  push:
    tags:
      - '*'
jobs:
  publishBinaries:
    name: Build and publish binairies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build
        run: mvn -B deploy -Pe2e,integration-test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: backend/webapp/target/*-standelone.jar
          asset_name: ui-designer-$tag-standelone.jar
          tag: ${{ github.ref }}
          overwrite: true
