name: Publish binaries

on:
  workflow_dispatch:
    inputs:
      tagVersion:
        description: base tag version to publish
        default: 1.11.100
        required: true
  push:
    tags:
      - '1.*'
jobs:
  publishBinaries:
    name: Build, publish and upload binairies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tagVersion || github.ref }}
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: test
        shell: bash
        run: echo 'toto ${{github.event.inputs.tagVersion}} --- ${{github.ref}}'
#      - name: Publish artefact
#        uses: samuelmeuli/action-maven-publish@v1
#        with:
#          gpg_private_key: ${{ secrets.gpg_private_key }}
#          gpg_passphrase: ${{ secrets.gpg_passphrase }}
#          nexus_username: ${{ secrets.ossrh_username }}
#          nexus_password: ${{ secrets.ossrh_password }}
#        if: ${{ github.event.release.prerelease == 'false'}}
